version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: toplegalconsulting-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toplegalconsulting
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci'
    ]
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - toplegalconsulting-network

  web:
    build: .
    container_name: toplegalconsulting-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - toplegalconsulting-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: toplegalconsulting-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - toplegalconsulting-network

volumes:
  db_data:

networks:
  toplegalconsulting-network:
    driver: bridge
