name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: toplegalconsulting
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: docker-compose -f docker-compose.yml build

    - name: Run Docker containers
      run: docker-compose -f docker-compose.yml up -d

    - name: Wait for MySQL to be ready
      run: |
        while ! docker exec toplegalconsulting-db mysqladmin ping -h"127.0.0.1" --silent; do
          sleep 1
        done

    - name: Install Composer dependencies
      run: docker exec toplegalconsulting-web composer install --prefer-dist --no-progress

    - name: Run database migrations
      run: docker exec toplegalconsulting-web php artisan migrate

    - name: Add test script to composer.json
      run: |
        docker exec toplegalconsulting-web bash -c 'echo "{\"scripts\": {\"test\": \"vendor/bin/phpunit\"}}" > composer.json'

    - name: Run test suite
      run: docker exec toplegalconsulting-web composer run-script test
